language: python
python:
  - "3.7"
install:
  - pip install -e .
  - pip install pytest-cov codecov # Install packages for code coverage report
  script:
  - pytest --cov=src tests # Point to the source directory